In [1]:
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
#load the dataset
movies_data = pd.read_csv('movies.csv')

In [3]:
#first 5 rows of data
movies_data.head()

,index,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,cast,crew,director
0,0,237000000,Action Adventure Fantasy Science Fiction,http://www.avatarmovie.com/,19995,culture clash future space war space colony so...,en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,Sam Worthington Zoe Saldana Sigourney Weaver S...,"[{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...",James Cameron
1,1,300000000,Adventure Fantasy Action,http://disney.go.com/disneypictures/pirates/,285,ocean drug abuse exotic island east india trad...,en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,Johnny Depp Orlando Bloom Keira Knightley Stel...,"[{'name': 'Dariusz Wolski', 'gender': 2, 'depa...",Gore Verbinski
2,2,245000000,Action Adventure Crime,http://www.sonypictures.com/movies/spectre/,206647,spy based on novel secret agent sequel mi6,en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,Daniel Craig Christoph Waltz L\u00e9a Seydoux ...,"[{'name': 'Thomas Newman', 'gender': 2, 'depar...",Sam Mendes
3,3,250000000,Action Crime Drama Thriller,http://www.thedarkknightrises.com/,49026,dc comics crime fighter terrorist secret ident...,en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,Christian Bale Michael Caine Gary Oldman Anne ...,"[{'name': 'Hans Zimmer', 'gender': 2, 'departm...",Christopher Nolan
4,4,260000000,Action Adventure Science Fiction,http://movies.disney.com/john-carter,49529,based on novel mars medallion space travel pri...,en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,Taylor Kitsch Lynn Collins Samantha Morton Wil...,"[{'name': 'Andrew Stanton', 'gender': 2, 'depa...",Andrew Stanton

In [5]:
#size of dataset
movies_data.shape

(4803, 24)

In [6]:
#selecting the relevent features for recommendation
selected_features = ['genres', 'keywords', 'title', 'cast', 'director']

In [8]:
#replacing the null values with null string
for feature in selected_features:
    movies_data[feature] = movies_data[feature].fillna('')

In [10]:
#Combining all the selected features
combined_features = movies_data['genres']+' '+movies_data['keywords']+' '+movies_data['title']+' '+movies_data['cast']+' '+movies_data['director']
print(combined_features)

0       Action Adventure Fantasy Science Fiction cultu...
1       Adventure Fantasy Action ocean drug abuse exot...
2       Action Adventure Crime spy based on novel secr...
3       Action Crime Drama Thriller dc comics crime fi...
4       Action Adventure Science Fiction based on nove...
                              ...
4798    Action Crime Thriller united states\u2013mexic...
4799    Comedy Romance  Newlyweds Edward Burns Kerry B...
4800    Comedy Drama Romance TV Movie date love at fir...
4801      Shanghai Calling Daniel Henney Eliza Coupe B...
4802    Documentary obsession camcorder crush dream gi...
Length: 4803, dtype: object

In [11]:
#Converting the text data into feature vectors
vectorizer = TfidfVectorizer()
feature_vectors = vectorizer.fit_transform(combined_features)
print(feature_vectors)

  (0, 170)	0.08164397506394089
  (0, 238)	0.09430085253959876
  (0, 5284)	0.11542535783031439
  (0, 13728)	0.10767939588044252
  (0, 5437)	0.10767939588044252
  (0, 3707)	0.22212670921932673
  (0, 3100)	0.23060174597886599
  (0, 5854)	0.18767372561034487
  (0, 14528)	0.3556081489155899
  (0, 16754)	0.13181785740568824
  (0, 3261)	0.25917503785940266
  (0, 14425)	0.22212670921932673
  (0, 1036)	0.2962233664994786
  (0, 13480)	0.15571157345215322
  (0, 17158)	0.2455016020784442
  (0, 17448)	0.20845327343836828
  (0, 13450)	0.22609868792212615
  (0, 14211)	0.2138604832941835
  (0, 16831)	0.20604347408586016
  (0, 14767)	0.1573177266234224
  (0, 8839)	0.23580014500028518
  (0, 10322)	0.1667461227601918
  (0, 13148)	0.20168608727942994
  (0, 7809)	0.11754904703299245
  (0, 2471)	0.1793489022038912
  :	:
  (4801, 17420)	0.29610091929880594
  (4801, 2450)	0.29610091929880594
  (4801, 13306)	0.29610091929880594
  (4801, 3535)	0.3104301279254694
  (4801, 14085)	0.3104301279254694
  (4801, 7321)	0.3104301279254694
  (4802, 11296)	0.16706679682542733
  (4802, 4536)	0.16390827507018593
  (4802, 2148)	0.2803547893952574
  (4802, 5016)	0.1454212711195024
  (4802, 17074)	0.15845823302392728
  (4802, 6178)	0.16105691467382952
  (4802, 3457)	0.1967531646568835
  (4802, 3893)	0.19020480999739653
  (4802, 4552)	0.3510181885987753
  (4802, 1318)	0.17734381221321624
  (4802, 13109)	0.15302505645417253
  (4802, 4375)	0.13912921440625242
  (4802, 6453)	0.1967531646568835
  (4802, 4643)	0.21709421212519517
  (4802, 10837)	0.16390827507018593
  (4802, 3680)	0.23088690493401984
  (4802, 2465)	0.21709421212519517
  (4802, 5367)	0.20774889176205064
  (4802, 7039)	0.5155526141236371

In [12]:
#getting the similarity score using cosine similarity
similarity = cosine_similarity(feature_vectors)

In [13]:
print(similarity)

[[1.         0.0237934  0.04095406 ... 0.         0.         0.        ]
 [0.0237934  1.         0.01318767 ... 0.03982525 0.         0.        ]
 [0.04095406 0.01318767 1.         ... 0.         0.05773922 0.        ]
 ...
 [0.         0.03982525 0.         ... 1.         0.         0.05747071]
 [0.         0.         0.05773922 ... 0.         1.         0.        ]
 [0.         0.         0.         ... 0.05747071 0.         1.        ]]

In [14]:
similarity.shape

(4803, 4803)

In [22]:
#Getting the movie name from the user
movie_name = input("Enter your favourite movie name: ")

#creating the list of movie names
list_of_all_titles = movies_data['title'].tolist()

#finding the close match for the movie given by user
close_matches_list = difflib.get_close_matches(movie_name, list_of_all_titles)
close_match = close_matches_list[0]

#finding the index of the movie using title
index_of_the_movie = movies_data[movies_data.title == close_match]['index'].values[0]

#getting the list of similar movies
simiilarity_score = list(enumerate(similarity[index_of_the_movie]))

#Sorting the movies based on similarity score
sorted_similar_movies = sorted(simiilarity_score, key = lambda x:x[1], reverse=True)

#printing the name of similar movies based on the index
print("Movies recommended for you: \n")

i=1
for movie in sorted_similar_movies:
    similar_movie = movies_data[movies_data.index == movie[0]]['title'].values[0]
    if(i<=20):
        print(i,'.',similar_movie)
        i+=1

Enter your favourite movie name:  avatar

Movies recommended for you:

1 . Avatar
2 . Guardians of the Galaxy
3 . Aliens
4 . Alien
5 . Galaxy Quest
6 . Star Trek Into Darkness
7 . Star Trek Beyond
8 . Space Dogs
9 . Jason X
10 . Alien³
11 . Gravity
12 . Lost in Space
13 . Zathura: A Space Adventure
14 . Cargo
15 . Trekkies
16 . Space Chimps
17 . Pocahontas
18 . Lockout
19 . Space Cowboys
20 . Machete Kills